sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BTM41cjbf2r/xgKGtRnq2YWwiY0o7FYSj1D40oA+4khbWJ7Y/AIkTh/BO6TyJdoAU2kQJEXmiRxxwjfMEAk6+Wmqs64H8UbdBcUVtUM8x8emfcTYZIpQbDB2rBm8hNOLqXMzYbI+vrsrxHQ5WesdVu6VWX8LKvUkAJKuYpC/1KpcX6194FEdI5Lsf/mrGjduqTdOWh6NMgUo2PM6wHKydJ1Wjt8Ffx1ZgZtv4gVgljuZzwVrvt7Q003kixhoVkvyU/GxAtFAtAb8doYWRu9p2FM1OcCAgKu1YJuKJQxAh7XZcKtUgAT3Z1e99ajikzRLyHJZHi16hh6jl9eeq9U+fanv4J0UeKRKDG25s637WkV7r2x9PjSLciDTRYGgRM4c1wf+rNmFvTioKakO4g8jjZ7nrXsLnEe84XYp5M94WPrC5bxkaFDvrZYlH8V+3rTBOqoip732zIh/WrLuMnppwkHYbqFJRoFXp6H741vnxW2+lF3k/fNYdbhvy5qAqdXL3pclSECPeZbWDQ4rm6dQPxg22BAhgSQNsWACXVDd81vty4NSfnzw7N+P8XNkeO4JisoXa8WxyhLCiKVH9qfYH3EnG5icPvqMb7fYhUADj0GsrLtqVO1+vx5KwflmmY99wEBiibFHdj9ObOvzH1NxsXFhS+ny8EA0oUvty0z9mHE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tom-Swift-in-the-Caves-of-Ice-or-the-Wreck-of-the-Airship_3734
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy